#!/usr/bin/env bash
# A script that enables nginx through port 80

# removes the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure Ngnix to ;isten on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart ngnix
service nginx restart
